[package]
name = "walletvalue"
version = "0.1.0"
authors = ["Kurtis Nusbaum <kcommiter@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_yaml = "0.7.3"
